### ISSUE TITLE
[PE-D][Tester A] `t=` not shown in UG for adding client and related commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-2/tp#131]
EDIT: I realized that the feature is not documented as it is not meant for the user to invoke but the functionality still exists. I made a separate issue describing another bug that arised from this in "Filtering tag does not work on falsefully created tags"

Commands that accept the input `t=` for tags work but not reflected in the UG. Would help if the UG could reflect such valid inputs but not a very major bug.

![image.png](https://raw.githubusercontent.com/BlopApple/ped/master/files/faa73d1c-0c26-44c5-af15-c33af4491c96.png)

For example in editing a client:

Before:

![image.png](https://raw.githubusercontent.com/BlopApple/ped/master/files/c6436685-4370-41ee-800f-8f7f98f38857.png)

After input: edit t=newtag1 t=newtag2
![image.png](https://raw.githubusercontent.com/BlopApple/ped/master/files/c9ed5f34-bcab-4c0a-899f-aff3a8be5b9c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: BlopApple/ped#3

**Comment by malwaregarry** [comment]
Merging with #122
