### ISSUE TITLE
[PE-D][Tester D] Bug: Unable to create multiple tags like the one shown in example specified in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-2/tp#137]
Using the examples provided in the UG, I was not able to run this command as an error message was seen instead: `tag create potential high-priority low-priority`

Following examples in the UG, this command is expected to be able to run smoothly, but in actual, it fails.

If as specified in the examples in the UG, that clients are able to create such tags with '-', maybe it is possible to allow the regex '-' to be included when checking for the creation of a valid tag?

![image.png](https://raw.githubusercontent.com/drkkjh/ped/main/files/60ad10dd-efec-4eda-8c43-f44630e1d8a5.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: drkkjh/ped#3

**Comment by malwaregarry** [comment]
Merging with #139
