### ISSUE TITLE
[PE-D][Tester E] tag create Command is not working as documented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-2/tp#139]
![Screenshot 2022-10-28 at 4.51.14 PM.png](https://raw.githubusercontent.com/elizabethhky/ped/main/files/958693e9-3052-4b2d-b0fe-52a126f4f600.png)

![Screenshot 2022-10-28 at 4.51.25 PM.png](https://raw.githubusercontent.com/elizabethhky/ped/main/files/a7dfdd69-e21f-4cf6-83e5-076f12bd3d3c.png)

Even though I used the supposedly valid input given in the User Guide, the command is unable to run. Is this supposed to occur?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: elizabethhky/ped#10

**Comment by malwaregarry** [comment]
Fixed in #152
